services:
  - name: fb-reaction-booster
    type: web
    runtime: python
    repo: https://github.com/YOUR_GITHUB_USERNAME/fb-reaction-booster
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
