services:
  - type: web
    name: weboost
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        value: "b5c6ba00bff9f5bdaef120129a560466bce3db23116f583a042f5540f55be8b9"
