services:
  - name: Weboost
    type: web
    runtime: python
    repo: https://github.com/Kayden200/Weboost
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
